pipeline {
    agent any

    parameters {
        string(name: 'EC2_PUBLIC_IP', defaultValue: '', description: 'Public IP of the EC2 instance for backend URL')
        string(name: 'S3_BUCKET', defaultValue: 'webchat-frontend-bucket', description: 'Name of the S3 bucket for the client')
    }
    environment {
        AWS_REGION = 'eu-north-1'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/MarioPeperoni/WebChat'
            }
        }

        stage('Inject Environment Variables') {
            steps {
                dir('frontend') {
                    sh '''
                        echo "VITE_BACKEND_URL=${EC2_PUBLIC_IP}" > .env
                    '''
                }
            }
        }

        stage('Build Static Files') {
            steps {
                dir('frontend') {
                    sh 'bun install'
                    sh 'bun run build'
                }
            }
        }

        stage("Deploy to S3") {
            steps {
                withAWS(credentials: 'aws-credentials') {
                    s3Upload(
                        bucket: "${S3_BUCKET}",
                        path: '',
                        includePathPattern: '**/*',
                        workingDir: 'frontend/dist',
                    )
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}