pipeline {
    agent any

    environment {
        S3_BUCKET = 'webchat-frontend-bucket'
        AWS_REGION = 'eu-north-1'
        EC2_PUBLIC_IP = ''
    }

    stages {
        stage("Inject Environment Variables") {
            steps {
                dir('frontend') {
                    sh """
                        echo "VITE_BACKEND_URL=${env.EC2_PUBLIC_IP}" > .env
                    """
                }
            }
        }

        stage("Build Static Files") {
            steps {
                dir('frontend') {
                    sh 'bun install'
                    sh 'bun run build'
                }
            }
        }

        stage("Deploy to S3") {
            steps {
                withAWS(credentials:'aws-credentials'){
                    s3Upload(
                        bucket: env.S3_BUCKET,
                        path: '',
                        includePathPattern: '**/*',
                        workingDir: 'frontend/dist',
                    )
                }
            }
        }
    }
    
}