- name: Install Docker
  dnf:
    name:
      - docker
      - python3-pip
      - python3-docker
    state: present
    update_cache: yes

- name: Enable and start Docker
  systemd:
    name: docker
    state: started
    enabled: yes